{% set name = "authenticatorpy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abdullahselek/authenticatorpy/archive/{{ version }}.tar.gz
  sha256: 2ca01ac22c1df5fec93ff450d6c6ba1468f4f2fb4ce8147d450b678b10a66f8f

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - authenticatorpy

about:
  home: https://github.com/abdullahselek/authenticatorpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python library that provide unique keys for 2FA with given secret.'
  description: |
    A Python library that provide unique keys for 2FA with given secret.
  doc_url: https://authenticatorpy.abdullahselek.com/
  dev_url: https://github.com/abdullahselek/authenticatorpy

extra:
  recipe-maintainers:
    - abdullahselek
